FROM node:20 AS build


WORKDIR /app
COPY config/node/frontend/package.json .
RUN npm install

COPY config/node/frontend .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /vsr/share/nginx/html